### ISSUE TITLE
"Styles" list in JCE Pro editor doesn't work

### ISSUE THREAD

**Issue by fontanil** [templaza/astroid-framework#219]
Hi,

I'm using Astroid One and Zero on some sites, and Joomlaplates templates too.
In the editor, the styles list is freezed with One and Zero, with Sounds from Joomlaplates too. No problem with Hope from Joomlaplates nor with Cassiopeia.
I opened threads on JCE and Joomlaplates forums too.

Same problem with JCE core. Core and Pro are 2.9.30, Astroid Framework 2.6.1, One and Zero 2.6.0, Sounds 1.3.10

**Comment by Chacapamac** [comment]
**Yes, I just realized the same thing on my tests.** 

Even if you have a **custom.scss** file in the normal **YourTemplate > scss > custom** folder, the compiled css go to that "**media/templates/site**" folder.
By doing this JCE cannot reach the css styles anymore
Same problem here with custom fonts (assign in the css files) —> https://github.com/templaza/astroid-framework/issues/210#issuecomment-1272547754

Seem to be resolved by Developer branch — I’m trying right now

**This is really bad as this change will break many websites**

**Comment by Chacapamac** [comment]
**Just a note on a strange behavior when Updating**

**If I start with that:**
![Joomla 4 - 1](https://user-images.githubusercontent.com/1907276/194887655-d4262142-a0ba-40c1-826b-fcd660b39030.jpg)

And update to Astroid 2.6.1 by the normal Joomla “**Update Extensions**” components the Astroid Package does not update to 2.6.1 — Only update if you re-install the package file —> astroid-package-v2.6.1.Framework-Template.zip over by using the normal “Joomla Upload” extensions

**Normal Joomla Update Extension**
![Normal-update](https://user-images.githubusercontent.com/1907276/194888679-5d01e757-8ffd-402d-a148-5dfaa60f580f.jpg)

**Reinstall by Joomla upload extension**
![re-install-by-upload](https://user-images.githubusercontent.com/1907276/194888942-b226d21c-64c3-4fa4-a560-e3fcdc53d38c.jpg)

• Even here, on my starting state, I think that both Template Zeo & One where Update to 2.6.0 only by reinstalling a full package, they never show in the normal **Joomla Update Extensions** warning

**Comment by Chacapamac** [comment]
**Just install the last Developer branch file and frontend is gone with error**
![Develloper-Branch](https://user-images.githubusercontent.com/1907276/194895335-de858802-5831-4baa-a833-85abc3a6f727.jpg)

**Comment by sonvnn** [comment]
Thanks for report bug! It related scss compile issue. I will check it when I back to office tomorrow.

Best regards,
Sonny

**Comment by sonvnn** [comment]
> **Just a note on a strange behavior when Updating**
> 
> 
> 
> **If I start with that:**
> 
> ![Joomla 4 - 1](https://user-images.githubusercontent.com/1907276/194887655-d4262142-a0ba-40c1-826b-fcd660b39030.jpg)
> 
> 
> 
> 
> 
> And update to Astroid 2.6.1 by the normal Joomla “**Update Extensions**” components the Astroid Package does not update to 2.6.1 — Only update if you re-install the package file —> astroid-package-v2.6.1.Framework-Template.zip over by using the normal “**Joomla Upload” extensions**
> 
> 
> 
> **Normal Joomla Update Extension**
> 
> ![Normal-update](https://user-images.githubusercontent.com/1907276/194888679-5d01e757-8ffd-402d-a148-5dfaa60f580f.jpg)
> 
> 
> 
> 
> 
> **Reinstall by Joomla upload extension**
> 
> ![re-install-by-upload](https://user-images.githubusercontent.com/1907276/194888942-b226d21c-64c3-4fa4-a560-e3fcdc53d38c.jpg)
> 
> 
> 
> • Even here, on my starting state, I think that both Template Zeo & One where Update to 2.6.0 only by reinstalling a full package, they never show in the normal **Joomla Update Extensions** warning
> 
> 

This happen because Joomla normal update is using to update library only not package.

When you upload package that includes library, one template and zero template it will install all extensions. It use for first install only. 

If user is using Astroid only or would like update Astroid only. They don't want to update templates because they might override their custom code. That is reason.

**Comment by sonvnn** [comment]
> **Just install the last Developer branch file and frontend is gone with error**
> 
> ![Develloper-Branch](https://user-images.githubusercontent.com/1907276/194895335-de858802-5831-4baa-a833-85abc3a6f727.jpg)

Hi @Chacapamac 

This issue happens because you placed `/custom/custom.scss` in wrong place. It should be placed in same location with `scss/style.scss`

Please help me check if your style.scss file placed in `media/templates/site/{your-template}/scss`. Please help me move `/custom/custom.scss` to same place

Thanks & Best Regards,
Sonny

**Comment by sonvnn** [comment]
> Hi,
> 
> I'm using Astroid One and Zero on some sites, and Joomlaplates templates too. In the editor, the styles list is freezed with One and Zero, with Sounds from Joomlaplates too. No problem with Hope from Joomlaplates nor with Cassiopeia. I opened threads on JCE and Joomlaplates forums too.
> 
> Same problem with JCE core. Core and Pro are 2.9.30, Astroid Framework 2.6.1, One and Zero 2.6.0, Sounds 1.3.10

Hi @fontanil ,

May you send me your admin account or screenshots of issue? I test JCE on my localhost, It still works well. It's very strange for me.

Thanks & Best Regards,
Sonny

**Comment by fontanil** [comment]
Hi @sonvnn,

I had the problem in a client's website with Astroid One. The custom.css file is in media/templates/site/astroid_template_one/css and it's the only website using a custom.css file. I didn't add a copy in scss folder.
On other sites using the same template, without custom.css, same problem: the styles list is empty. Same problem with several templates (One, Zero, Me, Sounds from Joomlaplates, not with Hope).
I created yesterday a new site with JCE, Astroid plus One and Zero, the Hope, Sounds and Me. No changes in the options, same problem.
I just verified another site using One without custom.css (only in the style template custom css tab), same problem.
The issue occurs on multiple client servers and on my local server (Wampserver).

I checked the templates folders ad files of the new site on the local server: the css folder is only in media/templates/site but no css file (One, Zero and Sounds). See the screenshots.
![image](https://user-images.githubusercontent.com/8665970/195021053-a19d1c25-8340-4f08-8047-d889a70b15c3.png)
![Capture d’écran 2022-10-11 091440](https://user-images.githubusercontent.com/8665970/195021304-044ef8df-6629-42d2-ae8b-03775aad7597.jpg)

**Comment by sonvnn** [comment]
Hi @fontanil ,

I am sorry but I don't understand about your issue, clearly. May you create a video describe your issue? 

Thank You & Best Regards,
Sonny

**Comment by fontanil** [comment]
This morning I checked 16 remote sites:

- 7 are using Astroid One: all have a styles list empty
- 1 is using Zero: same issue
- 3 are using Joomlaplates Easy: 2 have the issue, not the third!
- 1 is using Joomlplates Business whithout issue, but If I change to One, the error reappears
- 3 are using Joomlaplates Me, Brush or Hope: no issue
- 1 is using Joomlaplate Sounds and have the issue.

All are using Joomla! 4.2.3 and the last versions of Framework and templates. PHP is 8.0 on most, 8.1 on 2 (using Astroid Template One)

**Comment by sonvnn** [comment]
@Chacapamac @Joomlaplates May you help me detail his issue? May be in video or screenshot detail step by step to reproduce issue.

@fontanil I am sorry! I am not expert of JCE. If you can't detail your issue. I can not help. We did not received any issue with Astroid 2.6.1 from TemPlaza user yet.

Best regards,
Sonny

**Comment by fontanil** [comment]
In the JCE editor, there is a "styles" list: in 9 sites using One or Zero and 3 using Joomlaplates templates that list is empty, while it's populated with Cassiopeia.
![image](https://user-images.githubusercontent.com/8665970/195105474-13a1198e-ad53-4902-a0bb-bd1b2582bc00.png)
![image](https://user-images.githubusercontent.com/8665970/195105819-c7084aeb-7178-4fea-a597-0b8ea9237c9b.png)

**Comment by sonvnn** [comment]
> In the JCE editor, there is a "styles" list: in 9 sites using One or Zero and 3 using Joomlaplates templates that list is empty, while it's populated with Cassiopeia.
> 
> ![image](https://user-images.githubusercontent.com/8665970/195105474-13a1198e-ad53-4902-a0bb-bd1b2582bc00.png)
> 
> ![image](https://user-images.githubusercontent.com/8665970/195105819-c7084aeb-7178-4fea-a597-0b8ea9237c9b.png)
> 
> 

Thanks for your screenshots. That is what I need. I will test it on my localhost when I back to office tomorrow.

**Comment by fontanil** [comment]
Thanks Sonny!

I think I found. If in the profile "Typography" tab we add a "Custom CSS" file named
`media/templates/site/$tempalte/scss/style.css`
the JCE styles list is populated.
But we need to add this on each site where Astroid One or Zero (and some Joomlaplates templates) and JCE are used. It's not easy.
I informed Ryan of JCE

**Comment by fontanil** [comment]
Sorry, I'm confused! :(
I didn't test this change with One but with Cassiopeia...
No changes with One,
I'm looking for the JCE 2.9.31 beta 6 to test.

**Comment by fontanil** [comment]
Is it normal that I don't have any css files compiled in the media/templates/site/astroid_template_one/css folder but only in templates/astroid_template_one/css?
No more compiled files in templates/astroid_template_one/css

How to compile?

**Comment by fontanil** [comment]
Hi,

I uninstalled and reinstalled Astroid One on a site where I couldn't get compiled files and now there are some (and the template/astroid_template_one folder has been cleaned of folders no longer needed).

And Ryan (JCE) published a beta 6 version of the editor, solving the styles list issue. 
Thanks to all!

**Comment by sonvnn** [comment]
@fontanil I fixed this issue on https://github.com/templaza/astroid-framework/pull/223/commits/eee261c01bbfacfc23ae4507baafe16bb84388e3

Please help me download/update developer branch https://github.com/templaza/astroid-framework/archive/refs/heads/developer.zip

### For testing

1. After update successfully, please click "Astroid Clear Cache" button on top bar to clear Astroid Cache. 
2. Go to article and test JCE again.

Please let me know if this issue happens again.
Thanks & Best Regards,
Sonny

**Comment by fontanil** [comment]
Hi Sonny,

I installed the developer version on 2 sites using Astroid One, cleaned the Astroid cache and the issue remains.
Then I installed JCE Pro 2.9.31 beta 6 and the syles list is well populated.

**Comment by sonvnn** [comment]
@fontanil I forgot that you need go to front-end click refresh to re-create template.css in media. After that you will see style list in JCE editor.

Best regards,
Sonny
