### ISSUE TITLE
J4 menu link administration - adjust margin and check popover error in js

### ISSUE THREAD

**Issue by djayko** [templaza/astroid-framework#27]
Hello,

I figured out the following two things:

1. At J4 backend menu administration, the astroid tab is moving outside the screen left hand (desktop)
2. I saw an js error by accident within firefox developer tools:

Details (see screenshot additionally):
```
Uncaught TypeError: $(...).popover is not a function
    link https://mydomain.com/media/astroid/assets/js/astroid-framework.js?v=bb44fa86ef6d00c5015d357a539c3b9b:722
astroid-framework.js:722:24
    link https://mydomain.com/media/astroid/assets/js/astroid-framework.js?v=bb44fa86ef6d00c5015d357a539c3b9b:722
```

And by the way big thank you for continuing the astroid framework!!

![2021-11-15 12_00_29-Menus_ Edit Item - Fotograf München - photo deluxe - Administration](https://user-images.githubusercontent.com/3375044/141771249-d1a5f1cc-d383-4fd5-bda8-21399628968c.png)

best Ayko

**Comment by Joomlaplates** [comment]
Hello,
please try this fix.
https://github.com/templaza/astroid-framework/issues/24

**Comment by djayko** [comment]
Hello,

I tried it. It doesn't help.
Both issues are still there.

I added the both files as mentioned and changed the head.php.

best regards,
Ayko

**Comment by sonvnn** [comment]
Hello @djayko 

I fixed this issue at https://github.com/templaza/astroid-framework/commit/3f335fa636b5c11933e985258e94642b6178ef57

Please try to download developer git to your site and test it.

Thanks & Best Regards,
Sonny

**Comment by djayko** [comment]
@sonvnn it works. no more popover.js errors

First issue -> wrong margin for CSS still exists.

file:
media/astroid/assets/css/astroid-menu-options.css

search `#astroid-menu-options{margin-left:-180px}`

nee to be set to 0px or deletion of CSS declaration.

best Ayko,

**Comment by sonvnn** [comment]
Hi @djayko ,

I am not sure about your issue. But it works well on my site.
![Screen Shot 2021-11-17 at 09 24 19](https://user-images.githubusercontent.com/3204103/142101567-af45915f-fdd5-430a-a92f-3bf08f2903ef.png)

Bests,
Sonny

**Comment by djayko** [comment]
@sonvnn You're right on my clean installation it works well. 
Than close this issue.
I will investigate on my site what's causing this error.

Thanks
