### ISSUE TITLE
Astroid not working under Joomla 5 Alpha 4 DEV

### ISSUE THREAD

**Issue by deltapapa01** [templaza/astroid-framework#362]
Hey guys,
I have tried a bit with the Joomla 5 Alpha 4 DEV.
Unfortunately, the framework could not be installed here, it comes an error message (red bar) but there is unfortunately nothing inside.
I tried to call the Astroid Plugin, which unfortunately was not there.
Then I turned on the Backward Compatibility Plugin and installed the Astroid framework again, error message at maximum.
After that the page was completely broken.
In the frontend it says: Class "JPlugin" not found".
In the backend comes the following error message:

Attempted to load class "JFactory" from the global namespace.
Did you forget a "use" statement?
Symfony\Component\ErrorHandler\Error\
ClassNotFoundError
in /html/cms/administrator/modules/mod_astroid_clear_cache/mod_astroid_clear_cache.php (line 16)
use Joomla\CMS\Extension\ExtensionHelper;use Joomla\CMS\Helper\ModuleHelper;use Joomla\CMS\HTML\HTMLHelper;$joomlaFilesExtensionId = ExtensionHelper::getExtensionRecord('joomla', 'file')->extension_id;$document = JFactory::getDocument();HTMLHelper::_('jquery. framework');$document->addScript(JUri::base('true').'/modules/mod_astroid_clear_cache/js/notify.min.js');$document->addScript(JUri::base('true'). '/modules/mod_astroid_clear_cache/js/script.js');require ModuleHelper::getLayoutPath('mod_astroid_clear_cache', $params->get('layout', 'default'));

Unfortunately, I can't get Astroid to run this way.

Astroid Framework: 2.6.5
PHP: 8.2.5
Joomla: https://developer.joomla.org/nightlies/Joomla_5.0.0-alpha4-dev-Development-Full_Package.zip

WBR,
deltapapa

**Comment by sonvnn** [comment]
Hi @deltapapa01 ,

Thanks for report issue. We have a lot of task to do with Joomla 5. I will check it and response later.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Just joining the conversation.
Good Day to All!

**Comment by fontanil** [comment]
Hi,

Joomla! 5 will add a compatibility plugin to solve these errors and let the authors make changes to their extensions. ;)
https://github.com/joomla/joomla-cms/tree/5.0-dev/plugins/system/compat

**Comment by deltapapa01** [comment]
Hi @ALL,
with the Nightly Build it works now with the System - Backward Compatibility Plugin:

https://forum.joomla.de/thread/19048-ready-for-joomla-5-liste-von-templates-frameworks-erweiterungen-und-plugins-die/?postID=137071#post137071

**Comment by sonvnn** [comment]
Thank you all! Please help me keep track of this thread. I'm working on Astroid 3 https://github.com/templaza/astroid-framework/tree/v3
It will also be compatible with Joomla 5. I'm sure of that, so don't worry about it. We have plenty of time to get ready to move J5.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
**Joomla 3** end of life is not even over, only the 17 of August 2023....
**Good News @sonvnn !**

**Comment by deltapapa01** [comment]
Hi Sonny,
I just installed the version v3 and the backend opened, very, very, very fast!!! I had to get used to the first moment, but I like it very well.
But I have also seen that there is still a lot of work ahead of you. If I should test something etc. then let me know.

WBR,
deltapapa

**Comment by sonvnn** [comment]
Thanks for interest! I will inform on discussion when v3 is ready.

**Comment by Chacapamac** [comment]
@deltapapa01 

> I just installed the version v3 and the backend opened, very, very, very fast!!! 
Cant wait to test, **GREAT!**

**Comment by deltapapa01** [comment]
Hello,
I made some more tests with Joomla 5 - Alpha 3 - Dev - Nightly Build.
Astroid can be installed after switching on the Backward Plugin, but then come quite a few error messages.
I have previously set the error reporting to maximum.
I have recorded the test here:

https://1drv.ms/v/s!Ar1_3t0lo0q1ifABCjK9mcKRZ68ukA?e=oDTITU

There especially deprecated classes cause problems

@sonvnn: Do you still plan a version 2.x of the Astroid Framework for Joomla 5, or should only version 3.x run under J5 in the future?

**Comment by sonvnn** [comment]
Both of v2 and 3 will compatible with Joomla 5. So don't worry about it. I will check Joomla 5 as soon as V3 is completed.

Best Regards,
Sonny

**Comment by deltapapa01** [comment]
Hi @sonvnn 
i check v3 with Joomla 5 RC and the error in frontend is still there:

Deprecated: Creation of dynamic property Astroid\Document::$modules is deprecated in /html/cms/libraries/astroid/framework/library/astroid/Document.php on line 582

Joomla 5 will coming out on Okt 18, will you be able to fix it by then?

**Comment by fontanil** [comment]
Hi,

Joomla 5 will come with a compatibility plugin, and hiding errors will cause no problem to use Astroid 3, I think. ;)

**Comment by sonvnn** [comment]
@fontanil @deltapapa01 
I haven't tried testing with Joomla 5 yet. Because it's still in the future tense. Currently I'm trying to get Astroid 3 to work best with Joomla 4. That's the most important thing. We have to make sure Astroid 3 works best with the Joomla stable version then we can think about the future.

Best Regards,
Sonny

**Comment by deltapapa01** [comment]
@fontanil @sonvnn 
I use 2 test sites. On one I have updated from Joomla 4.3.4 to 4.4, with Astroid v2.6.6. -> Test went through without problems, worked wonderfully. In Joomla 4.4. I then made the update to Astroid V3.0, also runs as far as I could see without problems. You can view the page here: https://p624550.mittwaldserver.info/cms/ (Is a customer site of mine, which I have previously ported from Joomla 3 to Joomla 4.

My other test site was previously on Joomla 4.3 -> update to Joomla 4.4, then update to Joomla 5.0 with Astroid V3. The Backward Compatibility Plugin is of course switched on, otherwise many extensions would not run at all, or the Joomla at update from 4.4 to 5.0 already broken. Unfortunately, on Joomla 5 but the frontend does not run. Take a look: https://p603133.mittwaldserver.info/cms/

@sonvnn 
With the timelines I understand you, but Joomla 4.4 and Joomla 5.0 are released at the same time: https://developer.joomla.org/roadmap.html
Means that many users on 18.10.2023 so as i now tested from Joomla 4.3.4 to Joomla 4.4. update (there run Astroid v2 and v3 yes wonderful) and then in the next step will immediately update to Joomla 5 (where the Astroid v3 does not work at the moment.) This could then quickly mean a broken frontend for many pages.
And since we are already at the RC release of Joomla 5, there is unfortunately not much time left.

**Comment by sonvnn** [comment]
@fontanil @deltapapa01 
I fixed all issues with Joomla 5 at https://github.com/templaza/astroid-framework/commit/5a9d08b2e464bc810b594af4321d4e08505f51bd#diff-1b72dfa350f0160875311cc075fa2ebbc5ba6e53c282cbc08f5820ce2fbe256a and https://github.com/templaza/astroid-framework/commit/353df3e723d9807abb92339ee8c2de8bf94a2bc5

Now you can re-download Astroid 3 and play with Joomla 5 here https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip

Please let me know if you find any issue on Joomla 5.

Thanks & Best Regards,
Sonny

**Comment by deltapapa01** [comment]
Hi @sonvnn 
you are the man, very nice 😊

I update Astroid v3 to the newest version, but frontend has still an error: ERROR 0 - Database not set in Joomla\Module\RelatedItems\Site\Helper\RelatedItemsHelper in /html/cms/libraries/vendor/joomla/database/src/DatabaseAwareTrait.php:43
You can check Call Stack here: https://p603133.mittwaldserver.info/cms/
I deinstall an install Framework and template (Zero), but is still happend.

2 Other small things:
1) When i enabled error reporting, on Cassiopeia i see this line in frontend:
![image](https://github.com/templaza/astroid-framework/assets/19833064/b97f9eef-8970-4761-bc09-f5b33938e793)

In Astroid V3 this information is missing.

2) When i save the template setting in template manager backend, in the right bottom corner i saw that template style is saving. But then it says:
![image](https://github.com/templaza/astroid-framework/assets/19833064/7f0918d4-0be5-4420-ad61-8f95201267d2)
But my template style in Joomla is called like this: 
![image](https://github.com/templaza/astroid-framework/assets/19833064/06868c15-c871-47e0-826e-a7315f72d887)

Many, many thanks again and best regards
deltapapa

**Comment by sonvnn** [comment]
@deltapapa01 It look like an Joomla issue. I am not sure. I tried another way as their suggestion in https://github.com/templaza/astroid-framework/commit/31d6c24da883a040d4513cc43e802905cd685076

Please help me download v3 and retest again.

Thanks & Best Regards,
Sonny

**Comment by deltapapa01** [comment]
hey @sonvnn ,
it's working on my testsite: https://p603133.mittwaldserver.info/cms/
Debug Panel is working too (now i disabled it on my test - site because security reason)

great, thank you very much, i will test v3 more and more, but in the moment it looks very good in J4.4 and J5.0

**Comment by fontanil** [comment]
Hi,

I just downloaded the zip and installed it (5.0.0RC3dev compatibility plugin enabled): no problem.
I installed the template One (2.6.5): no problem.
On frontend, I had these warning to several lines. I opened the template style, saved and closed. No more warnings...

Thanks sonvnn for your great work!
