### ISSUE TITLE
a href="javascript:void(0): Links are not crawlable Google PageSpeed Insights SEO

### ISSUE THREAD

**Issue by strizhakovanatalya** [templaza/astroid-framework#541]
Hello)
I’m getting this error from Google PageSpeed Insights:
Search engines may use href attributes on links to crawl websites. Ensure that the href attribute of anchor elements links to an appropriate destination, so more pages of the site can be discovered.
<a href="javascript:void(0);" class=" nav-link-item-id-243 nav-link item-link-separator item-level-1" data-drop-action="hover">

The problem is in the Menu item type “Separator”and there was no such error in the previous version Astroid 3.0.8
Can you please remove href="javascript:void(0)" in the next updates to fix the error Links are not crawlable Google PageSpeed Insights SEO?
Thank you)

**Comment by sonvnn** [comment]
I fixed the issue in https://github.com/templaza/astroid-framework/commit/2fbaaae593010ec6a110ab5292b6dd30a75c28b5

Please help me download v3-branch and re-test again.

Thanks & Best Regards,
Sonny

**Comment by strizhakovanatalya** [comment]
This solution didn't help((  Google PageSpeed still doesn't like it. My site had 99 points, but now only 85((
![page](https://github.com/templaza/astroid-framework/assets/49317308/60f14ba4-0eda-4630-8057-853bbfe66ce7)

**Comment by sonvnn** [comment]
@strizhakovanatalya I fixed it again. Please help me download v3-branch again.

Thanks,
Sonny

**Comment by strizhakovanatalya** [comment]
Yes, it works, the problem is gone. Thank you)
![page1](https://github.com/templaza/astroid-framework/assets/49317308/daae81dc-87cb-4d61-874b-624c4812fa87)
