### ISSUE TITLE
Is it possible to Export stuff from Template One to Template Two?

### ISSUE THREAD

**Issue by Giorgi625** [templaza/astroid-framework#561]
I already work with Template one on my websites, but I want to move them to Template Two. Before I remember there was Import/Export Settings option but I can not find it now.
I used this feature to move from template Zero to One.
So was this feature removed? Is there option to move in one action or should I do it manually?

**Comment by mac-joomla** [comment]
It is now called "Preset Profiles" at similar location in preferences of Astroid template where "import" and "Export" used to be, where you now can save and import "Presets"

**Comment by Giorgi625** [comment]
I tried this but it does not save. I click on save preset, then add name and description and click on button, it does not do anything. how long should I wait for this?

**Comment by mac-joomla** [comment]
Does it show in your list of presets where? Then you can do an export from this tile. Does this work?

**Comment by mac-joomla** [comment]
ok seems a problem there. Are you on recent versions of templates an framework? Did you try to use another browser or even just restarting the browser and/or computer? In my case it works with Safari 17.3 on MacOS 13.6.4

**Comment by Giorgi625** [comment]
Everything up to date. Joomla 5.0.2
I use mainly Opera. Browser restart did not help. 
I opened website using Chrome but same thing.

**Comment by mac-joomla** [comment]
Good luck, unfortunately for the moment I don't know what to do here…

**Comment by Giorgi625** [comment]
even template save button on top has infinite animation when I click on it, so I guess something is broken on this website.

**Comment by mac-joomla** [comment]
did you clear cache?

**Comment by Giorgi625** [comment]
yes I cleared cache

**Comment by Giorgi625** [comment]
nothing helped on that website, I even uninstalled Astroid fully and installed again but same problem, while on other website it works just fine.

**Comment by sonvnn** [comment]
@Giorgi625 may you send me your admin via sonlv@tenplaza.com? I will help you check it.

**Comment by Giorgi625** [comment]
Sent

**Comment by sonvnn** [comment]
Sorry I make a mistake on my Mobile. My email is sonlv@templaza.com. May you send me your admin again?

**Comment by sonvnn** [comment]
I received your email. I will check it on Monday. I will response you asap

**Comment by Giorgi625** [comment]
Ok, thank you

**Comment by sonvnn** [comment]
@Giorgi625 I fixed the issue on your site. Please help me check it. Thanks

**Comment by Giorgi625** [comment]
Thank you I will check and share results.

**Comment by Giorgi625** [comment]
I still have problem. So what I did: I installed backup from January 30th on localhost and saved preset into json file from there. This is preset for Template One which I had installed on my site. I imported this file to website which you fixed. So import feature works fine. Save template also works until I select my preset and after I try to save this arrows on template save button arrows on it just go round and round and do not save template with my preset.

**Comment by deltapapa01** [comment]
Hey, I still have the problem that I can't transfer my settings from Template Zero to Template Two. I get the following error message:

Preset did not uploaded yet1second ago
INVALID FILETYPE

Is it even possible to switch from Zero to Two at the moment?
WBR,
deltapapa

**Comment by deltapapa01** [comment]
Hey, @sonvnn did you have an idea, you have the time to update template zero and one to use the new blog feature? I would also switch to template two, but unfortunately the import does not work from template zero. 
Thank you very much and wbr,
deltapapa

**Comment by sonvnn** [comment]
Can you send me your admin? I will try to export/import settings to Two.

**Comment by deltapapa01** [comment]
Hey Sonny, i send you account data from my testsite. When it's working, i want to change all my other sites too.

Thank you and with best regards,
deltapapa

**Comment by sonvnn** [comment]
@deltapapa01 I am sorry for late reply. I tried to export data from One and import to Two. Astroid works like a charm. Can you send me your admin via sonlv@templaza.com again? I need to check it on your site.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
I’m Using AdminTools to &Interested in this post.

• @deltapapa01 , are your error was always “INVALID FILETYPE” when exporting/importing? 
• Did you check your server errors logs, maybe you will have more infos. Strange...

• AdminTools htacees creator block everything not needed by Joomla on creation of the .htacces file, but I never create any exception for Astroid?

• Maybe Astroid Export/Import are asking for a specific folder/file to be readable and accessible? 
• The FILETYPE error seem to point to something else...?

• Did you try to fix site files/folder permissions in Admintools before trying?

**Comment by deltapapa01** [comment]
Hi,
Okay, I've found the solution to my problem.
When I use Akeeba Admin Tools, it blocks the correct creation of the present file under: **_media/templates/site/astroid_template_two/astroid/presets_**
To solve the problem, a rule must be added to the htaccess file that allows access to this folder:

![image](https://github.com/templaza/astroid-framework/assets/19833064/dfdc55c7-42ab-49d8-8bd5-8a179266be7c)

Once this is done, the present file will be created correctly, stored under the path. If I now download the file to my PC and then upload it again, everything works without a problem.
I had noticed that my present files were only 9KB in size, and the correctly created present files were well over 107kb.
I then realized that the files had no content at all, only warnings!

One more small thing: When troubleshooting, I noticed that no debug information is displayed in Astroid Framework. We had this a long time ago, is there a trick?
Even if I switch the debug information to Yes in the framework plugin, nothing happens in the template. The same applies to the debug information from Joomla, which is not displayed at all in the Template Manager.

WBR,
deltapapa

**Comment by Chacapamac** [comment]
Great Stuff @deltapapa01 
**This should be added to the documentation as Akeeba Admintools is THE firewall used by all pro on Joomla.**

I just add the exception on my websites. Thanks @sonvnn to share! 👍 🚀

**Comment by deltapapa01** [comment]
Hi,
the import / export Files work fine after set the exception in Akeeba.

**Comment by Chacapamac** [comment]
Thanks!

**Comment by felixkat** [comment]
Closing as marked as solved.
