### ISSUE TITLE
[Issue] Google Font Not removed from code, when deactivated

### ISSUE THREAD

**Issue by raramuridesign** [templaza/astroid-framework#730]
@sonvnn 

**Describe the bug**
If I have a text logo and disable Google fonts, the referenc to the preconnect and the google font is still present. 

![image](https://github.com/user-attachments/assets/944a5fd9-9974-4a2c-8241-a20e18894f06)

**To Reproduce**
1. Go to template astroid_template_two 
2. Click on edit text logo and switch to default
3. View the source and the font is still there.
4. See screenshot above.

**Expected behavior**
If font is disabled to inherit, then it should remove the google reference. 

**System Informations (please complete the following information):**
 - Joomla Version: Joomla 5
 - PHP 8.3.x
 - Astroid Version 3.1.0

**Comment by Banuk1616** [comment]
I also had this problem here and had to search a lot until I realized that it was related to the logo settings.

https://github.com/templaza/astroid-framework/discussions/601


I don't know if Sonny can change this, but it would be great if it could be changed. I think it would be great if you could activate or deactivate the Google Fonts in the Astroid plugin, similar to the Fontawesome.

@Sonny
Could you please see if you can find a solution for this. If you don't notice this and you accidentally load the Google Fonts, you can get into big problems because of the GDPR.

**Comment by sonvnn** [comment]
I fixed this issue at https://github.com/templaza/astroid-framework/commit/3d897772e674da967bf2fe5676a68e7f2d84e413

PS: If you are using two please help me check all widgets, too. We have a text-logo in the footer of template. Please help me disable all google font on your site. It will works. I test on my local site and it works.

**Comment by patrickus33** [comment]
@sonvnn 
I've applied your fix but google fonts are still present in source code
I have of course cleared the Astroid and Firefox cache.

It's a real problem for european users due to RGPD.

	<link href="[https://fonts.gstatic.com?2d79ba](view-source:https://fonts.gstatic.com/?2d79ba)" rel="preconnect" />
	<link href="[https://fonts.googleapis.com/css2?family=Arizonia&amp;display=swap](view-source:https://fonts.googleapis.com/css2?family=Arizonia&display=swap)" rel="stylesheet" />

My typo config :
![typo](https://github.com/user-attachments/assets/1bf065ee-5d35-4a66-86fa-e331453c1cfa)

**Comment by sonvnn** [comment]
Please send me the admin acc via sonlv@templaza.com. I will help you check it.

**Comment by Banuk1616** [comment]
Hi Sonny, I have replaced the Utility.php and tested it on my development environment. First I selected a Google font for the logo and wrote a small logo text (I had an image logo without text before).

Result: The Google font was displayed in the code.

I then set it to show no logo.

Result: The Google font is not displayed in the code.

It seems to work fine now.

**Comment by patrickus33** [comment]
For me, no changes.
Google fonts are always loaded whatever I choose for the logo .

**Comment by Banuk1616** [comment]
I have just downloaded the Quickstart, installed it locally, exchanged the Utility.php and tested it. It now works fine there too and the logo text is no longer displayed if no logo is selected.

Have you checked all the widgets? Perhaps a Google font is still being loaded from a widget.

**Comment by patrickus33** [comment]
@Banuk1616
Your right, I've not checked all widgets.
I'll take a look asap!
Thank you for your help

**Comment by Banuk1616** [comment]
@Sonny

Wouldn't it be good if you could disable Google Fonts completely if you don't want to use them?

![Unbenannt](https://github.com/user-attachments/assets/dd774de7-96f1-4f2e-8a61-c695790d5f47)

**Comment by patrickus33** [comment]
@Banuk1616 
This is absolutely what it would take to be RGPD compliant

**Comment by sonvnn** [comment]
@patrickus33 That is footer widget, I mentioned above.

**Comment by sonvnn** [comment]
> I fixed this issue at https://github.com/templaza/astroid-framework/commit/3d897772e674da967bf2fe5676a68e7f2d84e413
> 
> 
> 
> PS: If you are using two please help me check all widgets, too. We have a text-logo in the footer of template. Please help me disable all google font on your site. It will works. I test on my local site and it works.

@patrickus33 I mentioned about it here

**Comment by raramuridesign** [comment]
@sonvnn 
I can confirm that 
1. Google font is removed if its a text logo ie your code update
2. If I have any widget loading and select a google font, then the google font loads.

I do like the option to disable google fonts completely, as I am sure that users would miss widgets when they are troubleshooting where this might load.

So far the template version Two is working perfectly. Thank you.
M
