### ISSUE TITLE
Bug Grid Widget

### ISSUE THREAD

**Issue by Dnsftl** [templaza/astroid-framework#838]
Bug
Grid widget --> Template --> Two and Jollyany

Bug Description:

When you set the layout of the images in the image options to "image overlay," the images are placed directly on the header. Only the bottom three images are fully visible, while the top three are partially hidden. The 100px top margin is ignored, and the widget is not displayed in the correct position. When you switch the layout back to "classic," the images are correctly positioned with a 100px margin at the top.

Steps to Reproduce:

Go to the template: Two or Jollyany  
Navigate to Sub Layouts --> [name of sublayout]
Go to the Grid widget --> Image Options --> Choose Layout
Toggle between "classic" and "image overlay" and observe the difference on the front end.

Expected Behavior:
The widget should remain in the same position as with the classic layout, displaying all images.

Screenshots:
![Classic Jollyany Schermopname_20-10-2024_143955_dev nvsp nl](https://github.com/user-attachments/assets/31d477bd-605f-4c73-91c4-acdf17930aa0)
![Classic Schermopname_20-10-2024_144348_dev nvsp nl](https://github.com/user-attachments/assets/6640355e-2d07-42d8-8477-249743d4a04f)
![Classic Two Schermopname_20-10-2024_213425_www zlddsign nl](https://github.com/user-attachments/assets/21dc84ed-b7f6-49ff-83b0-d7d73c4321ea)
![Overlay Jollyany Schermopname_20-10-2024_14434_dev nvsp nl](https://github.com/user-attachments/assets/599192ee-665b-4dc6-a423-f8fb9704a0ab)
![Overlay Schermopname_20-10-2024_144423_dev nvsp nl](https://github.com/user-attachments/assets/475de2bc-d74d-415d-8a2e-19aed2bee3ba)
![Overlay Two Schermopname_20-10-2024_21330_www zlddsign nl](https://github.com/user-attachments/assets/9d1490e2-0fd3-4f99-9dd5-328bd52ead0b)

System Information:

Joomla Version: 5.2.0
PHP Version: 8.3
Astroid Version: 3.1.6
Device: Laptop
Operating System: Windows 11
Browsers: Chrome, Firefox, Edge

Regards,

Dennis

**Comment by sonvnn** [comment]
@Dnsftl Thank you for report bugs. I fixed this issue at https://github.com/templaza/astroid-framework/commit/eadf01cdbe6e30929732293a78b5f203f12047b3

Please help me check it.
Best regards,
Sonny

**Comment by Dnsftl** [comment]
@sonvnn,

The bug in the grid widget has been fixed, it works fine now.

Regards,

Dennis

**Comment by Dnsftl** [comment]
@sonvnn,

There still appears to be a bug in the grid widget in version v3.1.7-rc4

The same problem as above repeats itself if you enable 'Enable image cover', in this case it does not matter whether 'Choose Layout' is set to classic or image overlay. The same problem also occurs in template two

if you turn off 'Enable image cover' then it is as it should be.

Screenshots

![Enable image cover _28-10-2024_125558_dev nvsp nl](https://github.com/user-attachments/assets/da294914-72fd-41b4-bc5f-cf75ed6d816d)

Front:
![Enable imagecover front 28-10-2024_12557_dev nvsp nl](https://github.com/user-attachments/assets/c20bf770-bfb8-4457-9c98-51ba55f18cfd)

'Enable image cover' disabled
![Enable imagecover is off_28-10-2024_131545_dev nvsp nl](https://github.com/user-attachments/assets/2de0018c-69a9-45e9-b3d6-9f35867c7aec)

Regards,

Dennis

**Comment by sonvnn** [comment]
I am sorry. But I can not reproduce your issue. I saw your website is still good here
![Screen Shot 2024-10-29 at 11 06 05](https://github.com/user-attachments/assets/9ec131a1-0967-400f-b938-624c49670c89)

**Comment by Dnsftl** [comment]
@sonvnn 
It is true that it is not visible to you now. I had turned off Enable Image Cover.  Now it's enabled again and you can see that the bug is still there.

**Comment by felixkat** [comment]
@Dnsftl There's been a few releases since you first reported.  Is this issue still outstanding?

**Comment by Dnsftl** [comment]
@felixkat 

Unfortunately, this issue is still not resolved and remains a bug. Even after the recent updates, the problem persists.

![Image](https://github.com/user-attachments/assets/8012ede5-e465-4a32-a4dd-83e1378869c5)

**Comment by felixkat** [comment]
Okay I will try and replicate.

**Comment by Dnsftl** [comment]
@felixkat 

If it's easier to check on the site, just let me know. It's a development/test site.
Then I'll make sure you get access.
