### ISSUE TITLE
Form Builder - Redirect option not working Astroid 3.1.9

### ISSUE THREAD

**Issue by Tomisslaw** [templaza/astroid-framework#953]
Joomla 5.2.3
Astroid 3.1.9

I made the web form in a Template. In the template the option to redirect was not enabled (I will try later to redirect it in the template). When editing the Form widget in the Article, and when I enable the redirect option, and fill it with the url, after saving, the url in the filed is lost (the field is empty), and the redirect do not work.

 
![image](https://github.com/user-attachments/assets/6820f26d-1edc-4cab-b50c-46fb718bc8b8)

**Comment by sonvnn** [comment]
@Tomisslaw I fixed this issue at https://github.com/templaza/astroid-framework/commit/c5a5b5abef2372c3c71a650470742a2b6ce6f574

Please help me download v3-branch and retest it.

WBR,
Sonny

**Comment by Tomisslaw** [comment]
> @Tomisslaw I fixed this issue at [c5a5b5a](https://github.com/templaza/astroid-framework/commit/c5a5b5abef2372c3c71a650470742a2b6ce6f574)
> 
> Please help me download v3-branch and retest it.
> 
> WBR, Sonny

There is some improvement, but the bug is still here. Now, the field in the Astroid backend remembers the entered web address, but by submitting the form, the site do not redirect. :/ 

![image](https://github.com/user-attachments/assets/f9b3d470-7ba9-459d-a2e3-c2274a519a93)

**Comment by sonvnn** [comment]
Let's to clear browser cache and try it again.

**Comment by Tomisslaw** [comment]
Sorry, my mistake. After clearing the cache and testing with another browser, all works as expected.
