### ISSUE TITLE
Issue with article blog in responsive view

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#973]
Hi Sonny,
there is a bootstrap syntax missing in article blog view. Its not responsive anymore after update the Astroid
Take a look here on mobile device
https://compassionate-bardeen.85-214-95-104.plesk.page/

..
There is a syntax missing > bootstrap syntax
New and wrong syntax
`row-cols-3`

Old and right syntax
`row-cols-lg-3`
..
Thank you, Peter

**Comment by WM-Loose** [comment]
I confirm the error. The responsive view for category blogs no longer works with Astroid 3.1.10. All columns are next to each other and are no longer displayed one below the other in mobile view.

There are already many calls from customers. 
I recommended that they reinstall Astroid 3.1.9 until the bug is fixed in 3.1.10.

**Comment by sonvnn** [comment]
@Joomlaplates My mistake. I fixed it at https://github.com/templaza/astroid-framework/commit/5219e07338a75d5bc941949c3c316e5542108c01. Please help me re-download 3.1.10 and test it https://github.com/templaza/astroid-framework/releases/download/v3.1.10/astroid-framework-3.1.10.zip

Best Regards,
Sonny

**Comment by WM-Loose** [comment]
I downloaded and installed the package from your link but the problem is not solved and everything is as before. 
Caches deleted but still not responsive to each other on a small display.

**Comment by sonvnn** [comment]
@WM-Loose If you are using Astroid Pro you can configure column on the x-small view. Menu -> edit Menu-item -> Blog Options -> Scroll-down to Responsive Options

![Image](https://github.com/user-attachments/assets/75ac4786-6f05-42ee-833d-c65c467f5135)

**Comment by WM-Loose** [comment]
Yes, that was exactly the problem. After updating Astroid Pro (new version has to be downloaded) I was able to open the settings for it. For users who don't use Astroid Pro, Your adjustment now works too. The category blog content is OK again. 
Thanks for the quick help.

Regards Dirk

**Comment by Joomlaplates** [comment]
Hi Sonny, thanks for the fast response.
I agree its working now.
Friendly regards, Peter

**Comment by felixkat** [comment]
Thanks for the updates @WM-Loose & @Joomlaplates will mark this as closed.

**Comment by felixkat** [comment]
> Hi Sonny this issue above is not fixed in new Astroid 3.1.10 or? Friendlz Regards, Peter

It's in the latest code but not necessarily in the latest release.

So download the latest code from here. 

https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip
